"""Shared helpers for MCP tool modules."""

from __future__ import annotations

import inspect
from collections.abc import Mapping, MutableMapping
from dataclasses import dataclass
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, ValidationError


class ToolModel(BaseModel):
    """Base class for Pydantic tool inputs."""

    model_config = ConfigDict(extra="forbid")


class EmptyParams(ToolModel):
    """Tool input with no fields."""


class NameParams(ToolModel):
    """Common name-only input."""

    name: str = Field(..., min_length=1)


@dataclass(frozen=True)
class ToolDefinition:
    """MCP tool metadata and callable."""

    name: str
    description: str
    input_model: type[BaseModel]
    handler: Any

    @property
    def input_schema(self) -> dict[str, Any]:
        """Return the JSON Schema generated by Pydantic."""
        return self.input_model.model_json_schema()


def structured_error(error: str, message: str, code: int = 400) -> dict[str, Any]:
    """Return the project error envelope."""
    return {"success": False, "error": error, "message": message, "code": code}


async def call_bridge(bridge: Any, tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    """Call Blender through common bridge method names."""
    for method_name in ("call_tool", "execute_tool", "send_command", "request", "call", "execute"):
        method = getattr(bridge, method_name, None)
        if method is None:
            continue
        result = method(tool_name, params)
        if inspect.isawaitable(result):
            result = await result
        return result
    return structured_error("BridgeUnavailable", "Bridge object has no supported call method.", 503)


async def dispatch_tool(
    bridge: Any,
    tool_name: str,
    model: type[BaseModel],
    params: Mapping[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    """Validate public params and forward the original payload to Blender."""
    raw = dict(params or {})
    raw.update(kwargs)
    try:
        model.model_validate(raw)
    except ValidationError as exc:
        return structured_error("InvalidParams", exc.errors()[0]["msg"], 400)
    return await call_bridge(bridge, tool_name, raw)


def make_tool(tool_name: str, model: type[BaseModel]) -> Any:
    """Create a bridge-forwarding async tool function."""

    async def tool(bridge: Any, params: Mapping[str, Any] | None = None, **kwargs: Any) -> dict[str, Any]:
        """Validate parameters and forward the command to Blender."""
        return await dispatch_tool(bridge, tool_name, model, params, **kwargs)

    tool.__name__ = tool_name
    return tool


def build_tools(specs: list[tuple[str, str, type[BaseModel]]]) -> dict[str, ToolDefinition]:
    """Build tool definitions from compact specs."""
    result: dict[str, ToolDefinition] = {}
    for name, description, model in specs:
        handler = make_tool(name, model)
        result[name] = ToolDefinition(name, description, model, handler)
    return result


def export_tools(namespace: dict[str, Any], tools: dict[str, ToolDefinition]) -> None:
    """Expose generated handlers as module globals."""
    for name, spec in tools.items():
        namespace[name] = spec.handler


def register_toolset(registry: Any, tools: dict[str, ToolDefinition]) -> Any:
    """Register generated tool definitions with common registry shapes."""
    for spec in tools.values():
        if hasattr(registry, "register_tool"):
            registry.register_tool(spec.name, spec.description, spec.input_schema, spec.handler)
        elif isinstance(registry, MutableMapping):
            registry[spec.name] = spec
        else:
            raise TypeError("registry must expose register_tool or be a mutable mapping")
    return registry
